### ISSUE TITLE
Error saving output file

### ISSUE THREAD

**Issue by ss32** [Max-Manning/passiveRadar#5]
Unsure if this is due to my source data formatting or a change in behavior due to a newer version of `numpy`, but I will log progress here and open a PR if/when I get it sorted.

My gut tells me it's something in the data since it fails 3/4 of the way through processing.

Full stack trace

```
-------------------------------------------------------------------
   RUNNING PASSIVE RADAR PROCESSING   
-------------------------------------------------------------------
Input file: outfile.hdf5
Using radio channel centered at 90.7 MHz with bandwidth 200.0 kHz
Input sample rate 1.8 MHz, IF sample rate 262.1 kHz
Maximum bistatic range 200.14 km with range resolution 1.14 km
Maximum Doppler shift 255.99 Hz with Doppler resolution 0.5000 Hz
Successfully loaded data.
Corrected a sample offset of 0 samples between channels
Saving range-doppler maps to to XAMBG_1011.hdf5, metadata to XAMBG_1011.npz
Output shape: (1024, 176, 1), dtype: complex64
[##############################          ] | 76% Completed | 101.32 ms
Traceback (most recent call last):
  File "/home/user/Radar/passiveRadar/main.py", line 235, in <module>
    main(config)
  File "/home/user/Radar/passiveRadar/main.py", line 215, in main
    da.store(xambg, d)
  File "/home/user/.local/lib/python3.10/site-packages/dask/array/core.py", line 1236, in store
    compute_as_if_collection(Array, store_dsk, map_keys, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/dask/base.py", line 369, in compute_as_if_collection
    return schedule(dsk2, keys, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/dask/threaded.py", line 90, in get
    results = get_async(
  File "/home/user/.local/lib/python3.10/site-packages/dask/local.py", line 512, in get_async
    raise_exception(exc, tb)
  File "/home/user/.local/lib/python3.10/site-packages/dask/local.py", line 320, in reraise
    raise exc
  File "/home/user/.local/lib/python3.10/site-packages/dask/local.py", line 225, in execute_task
    result = _execute_task(task, data)
  File "/home/user/.local/lib/python3.10/site-packages/dask/core.py", line 127, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/.local/lib/python3.10/site-packages/dask/optimization.py", line 995, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/user/.local/lib/python3.10/site-packages/dask/core.py", line 157, in get
    result = _execute_task(task, cache)
  File "/home/user/.local/lib/python3.10/site-packages/dask/core.py", line 127, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/Radar/passiveRadar/passiveRadar/clutter_removal.py", line 181, in LS_Filter_Multiple
    srvChannelFiltered = LS_Filter_Toeplitz(refChannel, 
  File "/home/user/Radar/passiveRadar/passiveRadar/clutter_removal.py", line 142, in LS_Filter_Toeplitz
    autocorrRef = xcorr(refChannelShift, refChannelShift, 0, 
  File "/home/user/Radar/passiveRadar/passiveRadar/signal_utils.py", line 31, in xcorr
    return signal.correlate(s1, np.pad(s2, (nlag, nlead), mode='constant'),
  File "/home/user/.local/lib/python3.10/site-packages/scipy/signal/_signaltools.py", line 241, in correlate
    return convolve(in1, _reverse_and_conj(in2), mode, method)
  File "/home/user/.local/lib/python3.10/site-packages/scipy/signal/_signaltools.py", line 1428, in convolve
    return np.convolve(volume, kernel, mode)
  File "<__array_function__ internals>", line 180, in convolve
  File "/home/user/.local/lib/python3.10/site-packages/numpy/core/numeric.py", line 849, in convolve
    raise ValueError('v cannot be empty')
ValueError: v cannot be empty
```

**Comment by ss32** [comment]
`refChannel` is empty, guess I need to record streams separately.  Related: the gnuradio block in the `README` shows both file sinks appending the same file.

```
-------------------------------------------------------------------
   RUNNING PASSIVE RADAR PROCESSING   
-------------------------------------------------------------------
Input file: outfile.hdf5
Using radio channel centered at 90.7 MHz with bandwidth 200.0 kHz
Input sample rate 1.8 MHz, IF sample rate 262.1 kHz
Maximum bistatic range 200.14 km with range resolution 1.14 km
Maximum Doppler shift 255.99 Hz with Doppler resolution 0.5000 Hz
Successfully loaded data.
Corrected a sample offset of 0 samples between channels
refChannelShift []
refChannelShift []
filterLen 175
peek 10
> /home/user/Radar/passiveRadar/passiveRadar/clutter_removal.py(159)LS_Filter_Toeplitz()
-> xcorrSrvRef = xcorr(srvChannel, refChannelShift, 0,
(Pdb) p refChannel
array([], dtype=complex64)
```

**Comment by ss32** [comment]
Same result with separate `target` and `reference` recordings.  It happens on the very first call to `LS_Filter_Toeplitz` 
![image](https://github.com/Max-Manning/passiveRadar/assets/4565287/d1d608d5-b4b1-469f-96a2-6d1aaf7d3d05)


Contents of my `config.txt` files
```
$ cat config_*.txt
PATH /ref.dat
RANK 1
DIMENSION-SIZES 1551636
INPUT-CLASS IN
INPUT-SIZE 8

PATH /target.dat
RANK 1
DIMENSION-SIZES 1551636
INPUT-CLASS IN
INPUT-SIZE 8
```

```
$ h5import target.dat -c config_target.txt ref.dat -c config_ref.txt -o ../passiveRadar/outfile.hdf5
```

`PRconfig.yaml`

```yaml
#########################     INPUT FILE OPTIONS     ########################## 

#HDF5 file containing the input data
input_file: 'outfile.hdf5'

# interleaved_channels indicates whether both input channels are stored in a 
# single field in the hdf5 file. If True, the reference and surveillance channel
# data are assumed to be interleaved like this:
#   [ ref_I[0], ref_Q[0], srv_I[0], srv_Q[0], ref_I[1], ref_Q[1] ... ] 
# Set this to False if the reference and surveillance channel data are
# stored in seperate fields. 
interleaved_input_channels: False

# Paths to the reference/ surveillance channels in the input file. Ignored if 
# interleaved_input_channels is True.
input_ref_path: '/ref.dat'  
input_srv_path: '/target.dat'

# Path to the interleaved data in the input file. Ignored if 
# interleaved_channels is False. 
interleaved_data_path: './'

##########################     OUTPUT FILE OPTIONS    ##########################

range_doppler_map_ftype: 'zarr' # file type for output- 'zarr' or 'hdf5'
output_fname: 'XAMBG_1011' # output base filename
num_frames: 1200 # number of range-doppler map frames to compute

##########################    INPUT DATA PARAMETERS    #########################

input_sample_rate: 1800000      # input sample rate in Hz
input_center_freq: 90800000    # input center frequency in Hz. channel_freq - bandwidth / 2
channel_freq: 90700000         # center frequency of the FM radio channel in Hz
channel_bandwidth: 200000       # channel bandwidth in Hz

#########################    PROCESSING PARAMETERS    ##########################

# Nominal value for the coherent processing interval in seconds. The doppler 
# resolution is inversely proportional to this, i.e. a 2 second CPI corresponds
# to a Doppler resolution of 0.5Hz.
cpi_seconds_nominal: 2.0
max_doppler_nominal: 256.0  # The maximum desired doppler shift in Hz. 
max_range_nominal: 200.0    # The maximum desired bistatic range in km.
overlap_cpi: True           # whether to overlap CPI windows. 
```

**Comment by ss32** [comment]
`ref_data` is being overwritten to 0 in line 121.

```python
ref_data = ref_data[0:N_chunks*config['input_chunk_length']//2]
```

`N_chunks` is 0 because both `N_chunks_ref` and `N_chunks_srv` are 1, and line 120 is subtracting 1.

**Comment by ss32** [comment]
Hardcoding a sane value for `N_chunks` on [line 118](https://github.com/Max-Manning/passiveRadar/blob/dca143ddbdac1c40c7af54a33bcb55ec8c489a2c/main.py#L118) seems to have corrected the error.  It's processing now, but I would like to know what a *good* value is rather than firing off some power of 2 assuming it's ok.
